# tasks file for ubuntu-2004-mariadb-server
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ ubuntu_2004_mariadb_server_dependencies }}"

- name: install | dependencies | check service
  ansible.builtin.service:
    name: mysql
    state: started
