# tasks file for ubuntu-2004-mariadb-server
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_2004_mariadb_server_dependencies }}"

- name: install | dependencies | check service
  service:
    name: mysql
    state: started
