# tasks file for ubuntu-2004-mariadb-server
---

- name: install
  ansible.builtin.import_tasks: install.yml

- name: configure
  ansible.builtin.import_tasks: configure.yml

- name: start and enable service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
