# tasks file for ubuntu-2004-mariadb-server
---

- include: install.yml

- include: configure.yml

- name: start and enable service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
